version: '3'

services:
  database:
    image: postgres:12.4-alpine
    container_name: "postgres-mavem"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mavem_db
    command:
      - "postgres"
      - "-c"
      - "effective_cache_size=1024MB"
    networks:
      - network-mavem
    volumes:
      - ./srv/docker/postgresql:/var/lib/postgresql

  app:
    build: .
    container_name: "spring-app"
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - network-mavem

volumes:
  data:
    driver: local

networks:
  network-mavem:
    driver: bridge