version: '3'

services:
  database:
    image: postgres:12.4-alpine
    container_name: "postgres-gradle"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gradle_db
    command:
      - "postgres"
      - "-c"
      - "effective_cache_size=1024MB"
    networks:
      - network-gradle
    volumes:
      - ./srv/docker/postgresql:/var/lib/postgresql

  app:
    build: .
    container_name: "spring-app"
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - network-gradle

volumes:
  data:
    driver: local

networks:
  network-gradle:
    driver: bridge